framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        cookie_secure: true       # important si tu es en HTTPS en prod
        cookie_samesite: lax
